// Mock Data Store for YCKF Dashboard
import type {
  User,
  Incident,
  Evidence,
  Notification,
  DashboardStats,
  IncidentTrend,
  SeverityDistribution,
  InvestigatorPerformance,
  VolunteerPerformance,
  RecentActivity,
} from './types'

// Helper to create dates relative to now
const daysAgo = (days: number) => new Date(Date.now() - days * 24 * 60 * 60 * 1000)
const hoursAgo = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000)

export const users: User[] = [
  {
    id: 'user-1',
    email: 'yckfadmin@youngcyberknightsfoundation.org',
    name: 'Sarah Chen',
    role: 'admin',
    avatar: undefined,
    status: 'active',
    createdAt: daysAgo(365),
    lastLogin: hoursAgo(1),
  },
  {
    id: 'user-2',
    email: 'mypracticalworks@gmail.com',
    name: 'Bright Peter Kwaku Boateng',
    role: 'volunteer',
    avatar: undefined,
    status: 'active',
    createdAt: daysAgo(180),
    lastLogin: hoursAgo(3),
  },
  {
    id: 'user-3',
    email: 'emily.watson@yckf.org',
    name: 'Emily Watson',
    role: 'volunteer',
    avatar: undefined,
    status: 'active',
    createdAt: daysAgo(120),
    lastLogin: hoursAgo(5),
  },
  {
    id: 'user-4',
    email: 'james.kim@yckf.org',
    name: 'James Kim',
    role: 'volunteer',
    avatar: undefined,
    status: 'active',
    createdAt: daysAgo(90),
    lastLogin: daysAgo(1),
  },
  {
    id: 'user-5',
    email: 'alex.patel@yckf.org',
    name: 'Alex Patel',
    role: 'admin',
    avatar: undefined,
    status: 'inactive',
    createdAt: daysAgo(200),
    lastLogin: daysAgo(30),
  },
]

export const incidents: Incident[] = [
  {
    id: 'inc-001',
    title: 'Ransomware Attack on Finance Server',
    description: 'Critical ransomware detected on the primary finance server. Files encrypted with .locked extension. Ransom note demands 5 BTC.',
    type: 'ransomware',
    severity: 'critical',
    status: 'investigating',
    assignedTo: 'user-2',
    assignedToName: 'Mike Torres',
    reportedBy: 'user-1',
    reportedByName: 'Sarah Chen',
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(1),
    notes: [
      {
        id: 'note-1',
        incidentId: 'inc-001',
        authorId: 'user-2',
        authorName: 'Mike Torres',
        content: 'Isolated affected server from network. Beginning forensic analysis.',
        createdAt: hoursAgo(5),
      },
      {
        id: 'note-2',
        incidentId: 'inc-001',
        authorId: 'user-2',
        authorName: 'Mike Torres',
        content: 'Identified entry point as phishing email received by accounting dept.',
        createdAt: hoursAgo(2),
      },
    ],
  },
  {
    id: 'inc-002',
    title: 'Phishing Campaign Targeting Employees',
    description: 'Multiple employees received sophisticated phishing emails impersonating IT department requesting password resets.',
    type: 'phishing',
    severity: 'high',
    status: 'investigating',
    assignedTo: 'user-3',
    assignedToName: 'Emily Watson',
    reportedBy: 'user-4',
    reportedByName: 'James Kim',
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(4),
    notes: [
      {
        id: 'note-3',
        incidentId: 'inc-002',
        authorId: 'user-3',
        authorName: 'Emily Watson',
        content: 'Blocked sender domain at email gateway. Analyzing email headers.',
        createdAt: hoursAgo(20),
      },
    ],
  },
  {
    id: 'inc-003',
    title: 'Unauthorized Data Access Attempt',
    description: 'Security logs show repeated unauthorized access attempts to customer database from external IP.',
    type: 'data_breach',
    severity: 'high',
    status: 'open',
    reportedBy: 'user-1',
    reportedByName: 'Sarah Chen',
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(2),
    notes: [],
  },
  {
    id: 'inc-004',
    title: 'DDoS Attack on Public Website',
    description: 'Website experiencing significant slowdown due to volumetric DDoS attack. Traffic peaked at 50Gbps.',
    type: 'ddos',
    severity: 'medium',
    status: 'resolved',
    assignedTo: 'user-4',
    assignedToName: 'James Kim',
    reportedBy: 'user-2',
    reportedByName: 'Mike Torres',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
    resolvedAt: daysAgo(2),
    notes: [
      {
        id: 'note-4',
        incidentId: 'inc-004',
        authorId: 'user-4',
        authorName: 'James Kim',
        content: 'Activated DDoS mitigation service. Traffic normalized.',
        createdAt: daysAgo(2),
      },
    ],
  },
  {
    id: 'inc-005',
    title: 'Malware Found on Marketing Workstation',
    description: 'Antivirus detected Emotet trojan on marketing team workstation. Machine quarantined.',
    type: 'malware',
    severity: 'medium',
    status: 'pending',
    assignedTo: 'user-3',
    assignedToName: 'Emily Watson',
    reportedBy: 'user-3',
    reportedByName: 'Emily Watson',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
    notes: [
      {
        id: 'note-5',
        incidentId: 'inc-005',
        authorId: 'user-3',
        authorName: 'Emily Watson',
        content: 'Workstation reimaged. Awaiting full network scan results.',
        createdAt: daysAgo(1),
      },
    ],
  },
  {
    id: 'inc-006',
    title: 'Suspicious Insider Activity Detected',
    description: 'Employee attempted to copy large amounts of sensitive data to external USB drive after hours.',
    type: 'insider_threat',
    severity: 'critical',
    status: 'investigating',
    assignedTo: 'user-1',
    assignedToName: 'Sarah Chen',
    reportedBy: 'user-2',
    reportedByName: 'Mike Torres',
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(8),
    notes: [
      {
        id: 'note-6',
        incidentId: 'inc-006',
        authorId: 'user-1',
        authorName: 'Sarah Chen',
        content: 'USB ports disabled company-wide. HR notified for investigation.',
        createdAt: hoursAgo(20),
      },
    ],
  },
  {
    id: 'inc-007',
    title: 'SSL Certificate Expiration Warning',
    description: 'Production SSL certificate expiring in 7 days. Renewal required.',
    type: 'other',
    severity: 'low',
    status: 'open',
    reportedBy: 'user-4',
    reportedByName: 'James Kim',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    notes: [],
  },
  {
    id: 'inc-008',
    title: 'Brute Force Attack on VPN',
    description: 'Multiple failed login attempts detected on corporate VPN from various IP addresses.',
    type: 'other',
    severity: 'medium',
    status: 'resolved',
    assignedTo: 'user-2',
    assignedToName: 'Mike Torres',
    reportedBy: 'user-1',
    reportedByName: 'Sarah Chen',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
    resolvedAt: daysAgo(4),
    notes: [
      {
        id: 'note-7',
        incidentId: 'inc-008',
        authorId: 'user-2',
        authorName: 'Mike Torres',
        content: 'Implemented rate limiting and geo-blocking. Attack mitigated.',
        createdAt: daysAgo(4),
      },
    ],
  },
  {
    id: 'inc-009',
    title: 'Compromised Admin Credentials',
    description: 'Admin account credentials found on dark web paste site. Immediate password reset required.',
    type: 'data_breach',
    severity: 'critical',
    status: 'closed',
    assignedTo: 'user-1',
    assignedToName: 'Sarah Chen',
    reportedBy: 'user-3',
    reportedByName: 'Emily Watson',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(5),
    resolvedAt: daysAgo(5),
    notes: [
      {
        id: 'note-8',
        incidentId: 'inc-009',
        authorId: 'user-1',
        authorName: 'Sarah Chen',
        content: 'All admin passwords reset. MFA enforced. Conducted security audit.',
        createdAt: daysAgo(6),
      },
    ],
  },
  {
    id: 'inc-010',
    title: 'Suspicious Network Traffic Pattern',
    description: 'Unusual outbound traffic detected to known C2 server IP addresses.',
    type: 'malware',
    severity: 'high',
    status: 'investigating',
    assignedTo: 'user-4',
    assignedToName: 'James Kim',
    reportedBy: 'user-2',
    reportedByName: 'Mike Torres',
    createdAt: hoursAgo(12),
    updatedAt: hoursAgo(6),
    notes: [
      {
        id: 'note-9',
        incidentId: 'inc-010',
        authorId: 'user-4',
        authorName: 'James Kim',
        content: 'Blocked C2 IP ranges at firewall. Investigating affected endpoints.',
        createdAt: hoursAgo(8),
      },
    ],
  },
]

export const evidence: Evidence[] = [
  {
    id: 'evd-001',
    incidentId: 'inc-001',
    incidentTitle: 'Ransomware Attack on Finance Server',
    filename: 'ransomware_sample.exe',
    fileType: 'application/x-executable',
    fileSize: 2458624,
    hash: 'a3f2b8c1d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1',
    uploadedBy: 'user-2',
    uploadedByName: 'Mike Torres',
    uploadedAt: hoursAgo(4),
    description: 'Captured ransomware executable from infected system',
    chainOfCustody: [
      {
        id: 'audit-1',
        action: 'Uploaded',
        performedBy: 'user-2',
        performedByName: 'Mike Torres',
        timestamp: hoursAgo(4),
        details: 'Initial capture from quarantined system',
      },
    ],
  },
  {
    id: 'evd-002',
    incidentId: 'inc-001',
    incidentTitle: 'Ransomware Attack on Finance Server',
    filename: 'ransom_note.txt',
    fileType: 'text/plain',
    fileSize: 1247,
    hash: 'b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5',
    uploadedBy: 'user-2',
    uploadedByName: 'Mike Torres',
    uploadedAt: hoursAgo(4),
    description: 'Ransom note left by attackers',
    chainOfCustody: [
      {
        id: 'audit-2',
        action: 'Uploaded',
        performedBy: 'user-2',
        performedByName: 'Mike Torres',
        timestamp: hoursAgo(4),
        details: 'Collected from encrypted directory',
      },
    ],
  },
  {
    id: 'evd-003',
    incidentId: 'inc-002',
    incidentTitle: 'Phishing Campaign Targeting Employees',
    filename: 'phishing_email.eml',
    fileType: 'message/rfc822',
    fileSize: 45678,
    hash: 'c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6',
    uploadedBy: 'user-3',
    uploadedByName: 'Emily Watson',
    uploadedAt: hoursAgo(20),
    description: 'Original phishing email with headers',
    chainOfCustody: [
      {
        id: 'audit-3',
        action: 'Uploaded',
        performedBy: 'user-3',
        performedByName: 'Emily Watson',
        timestamp: hoursAgo(20),
        details: 'Exported from affected user mailbox',
      },
      {
        id: 'audit-4',
        action: 'Analyzed',
        performedBy: 'user-3',
        performedByName: 'Emily Watson',
        timestamp: hoursAgo(18),
        details: 'Header analysis completed',
      },
    ],
  },
  {
    id: 'evd-004',
    incidentId: 'inc-006',
    incidentTitle: 'Suspicious Insider Activity Detected',
    filename: 'usb_activity_log.csv',
    fileType: 'text/csv',
    fileSize: 12890,
    hash: 'd6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7',
    uploadedBy: 'user-1',
    uploadedByName: 'Sarah Chen',
    uploadedAt: hoursAgo(20),
    description: 'USB device activity logs from endpoint',
    chainOfCustody: [
      {
        id: 'audit-5',
        action: 'Uploaded',
        performedBy: 'user-1',
        performedByName: 'Sarah Chen',
        timestamp: hoursAgo(20),
        details: 'Extracted from endpoint security software',
      },
    ],
  },
  {
    id: 'evd-005',
    incidentId: 'inc-010',
    incidentTitle: 'Suspicious Network Traffic Pattern',
    filename: 'network_capture.pcap',
    fileType: 'application/vnd.tcpdump.pcap',
    fileSize: 15728640,
    hash: 'e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8',
    uploadedBy: 'user-4',
    uploadedByName: 'James Kim',
    uploadedAt: hoursAgo(8),
    description: 'Network traffic capture showing C2 communication',
    chainOfCustody: [
      {
        id: 'audit-6',
        action: 'Uploaded',
        performedBy: 'user-4',
        performedByName: 'James Kim',
        timestamp: hoursAgo(8),
        details: 'Captured via network TAP',
      },
    ],
  },
]

export const notifications: Notification[] = [
  {
    id: 'notif-001',
    type: 'alert',
    title: 'Critical Incident Detected',
    message: 'A new critical ransomware incident has been reported. Immediate attention required.',
    priority: 'urgent',
    createdAt: hoursAgo(6),
    read: false,
    targetRoles: ['admin', 'volunteer'],
  },
  {
    id: 'notif-002',
    type: 'broadcast',
    title: 'Security Awareness: Phishing Alert',
    message: 'Multiple phishing attempts detected. Please verify sender addresses before clicking links.',
    priority: 'high',
    createdAt: daysAgo(1),
    read: true,
    targetRoles: ['admin', 'volunteer'],
  },
  {
    id: 'notif-003',
    type: 'notice',
    title: 'System Maintenance Scheduled',
    message: 'Security systems will undergo maintenance on Sunday 2AM-4AM UTC.',
    priority: 'normal',
    createdAt: daysAgo(2),
    read: true,
  },
  {
    id: 'notif-004',
    type: 'awareness',
    title: 'New Threat Intelligence Report',
    message: 'Q4 2024 threat landscape report is now available in the knowledge base.',
    priority: 'low',
    createdAt: daysAgo(3),
    read: false,
  },
  {
    id: 'notif-005',
    type: 'alert',
    title: 'Insider Threat Investigation',
    message: 'An insider threat investigation has been initiated. Check incident INC-006.',
    priority: 'high',
    createdAt: daysAgo(1),
    read: false,
    targetRoles: ['admin'],
  },
]

// Analytics Data
export function getDashboardStats(): DashboardStats {
  const total = incidents.length
  const open = incidents.filter(i => i.status === 'open').length
  const investigating = incidents.filter(i => i.status === 'investigating').length
  const pending = incidents.filter(i => i.status === 'pending').length
  const resolved = incidents.filter(i => i.status === 'resolved' || i.status === 'closed').length
  const critical = incidents.filter(i => i.severity === 'critical').length

  return {
    totalUsers: users.length,
    activeUsers: users.filter(u => u.status === 'active').length,
    totalIncidents: total,
    openIncidents: open,
    investigatingIncidents: investigating,
    pendingIncidents: pending,
    resolvedIncidents: resolved,
    criticalIncidents: critical,
    avgResponseTimeHours: 4.2,
  }
}

export function getIncidentTrends(): IncidentTrend[] {
  return [
    { date: '2024-01', incidents: 12, resolved: 10 },
    { date: '2024-02', incidents: 8, resolved: 7 },
    { date: '2024-03', incidents: 15, resolved: 12 },
    { date: '2024-04', incidents: 10, resolved: 9 },
    { date: '2024-05', incidents: 18, resolved: 14 },
    { date: '2024-06', incidents: 14, resolved: 13 },
    { date: '2024-07', incidents: 20, resolved: 16 },
    { date: '2024-08', incidents: 16, resolved: 15 },
    { date: '2024-09', incidents: 22, resolved: 18 },
    { date: '2024-10', incidents: 19, resolved: 17 },
    { date: '2024-11', incidents: 25, resolved: 20 },
    { date: '2024-12', incidents: 10, resolved: 6 },
  ]
}

export function getSeverityDistribution(): SeverityDistribution[] {
  return [
    { severity: 'critical', count: incidents.filter(i => i.severity === 'critical').length },
    { severity: 'high', count: incidents.filter(i => i.severity === 'high').length },
    { severity: 'medium', count: incidents.filter(i => i.severity === 'medium').length },
    { severity: 'low', count: incidents.filter(i => i.severity === 'low').length },
  ]
}

export function getVolunteerPerformance(): VolunteerPerformance[] {
  const volunteers = users.filter(u => u.role === 'volunteer')
  return volunteers.map(inv => ({
    name: inv.name.split(' ')[0],
    resolved: incidents.filter(i => i.assignedTo === inv.id && (i.status === 'resolved' || i.status === 'closed')).length,
    investigating: incidents.filter(i => i.assignedTo === inv.id && i.status === 'investigating').length,
  }))
}

export const getInvestigatorPerformance = getVolunteerPerformance

export function getRecentActivity(): RecentActivity[] {
  return [
    {
      id: 'act-1',
      action: 'Incident Updated',
      description: 'Mike Torres added a note to INC-001',
      user: 'Mike Torres',
      timestamp: hoursAgo(1),
      type: 'incident',
    },
    {
      id: 'act-2',
      action: 'Evidence Uploaded',
      description: 'Network capture uploaded for INC-010',
      user: 'James Kim',
      timestamp: hoursAgo(8),
      type: 'evidence',
    },
    {
      id: 'act-3',
      action: 'New Incident',
      description: 'Critical ransomware incident reported',
      user: 'Sarah Chen',
      timestamp: hoursAgo(6),
      type: 'incident',
    },
    {
      id: 'act-4',
      action: 'Status Changed',
      description: 'INC-004 marked as resolved',
      user: 'James Kim',
      timestamp: daysAgo(2),
      type: 'incident',
    },
    {
      id: 'act-5',
      action: 'Broadcast Sent',
      description: 'Phishing alert broadcast to all users',
      user: 'Sarah Chen',
      timestamp: daysAgo(1),
      type: 'notification',
    },
  ]
}
